### ISSUE TITLE
[FEA] Provide a way to exclude target columns from selections by tag

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/core#75]
**Is your feature request related to a problem? Please describe.**

I am using NVTabular to preprocess data of the recsys challenge: the label is the id of the purchased item (a multi-classification problem). 
One of the pre-processing steps is to encode the `purchased_item` column using the `Categorify` operator. The operator automatically generates the encoded feature tagged with `Tags.CATEGORICAL`. However, in our use case, we need to remove this tag to not use the label as an input to the model. 
 We can also think of other use cases where we generate new variables from parent features but we don't want to keep all the parent tags. 

**Describe the solution you'd like**
Similar to the `AddMetaData` operator, it would be great to have a `RemoveMetaData` op to remove unwanted tags/properties. 

**Describe alternatives you've considered**
I manually edited the schema file and removed the `categorical` tag from the `purchased_item` feature.

**Comment by karlhigley** [comment]
@sararb We've added the `excluding()` method, so this should now work with the latest version of `core`:

```python
schema.select_by_tag(Tags.CATEGORICAL).excluding(Tags.TARGET)
```

**Comment by sararb** [comment]
Thank you 🙏 As soon as I got some time, I will test it and update Merlin Models' code accordingly.

**Comment by karlhigley** [comment]
Ah, right. I have steered you wrong on how to actually use the API we implemented. You can do either:
```
self.schema.select_by_tag(Tags.CATEGORICAL).excluding(ColumnSelector(tags=Tags.TARGET)).column_names
```
(a bit clunky)
or:
```
self.schema.select_by_tag(Tags.CATEGORICAL).excluding_by_tag(Tags.TARGET).column_names
```

**Comment by marcromeyn** [comment]
Maybe we could add a check in `excluding` where we check whether a column-selector or tag is being passed in, and then process these accordingly?
